name: Coverage

on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - '**.md'
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'

jobs:
  coverage:
    name: Coverage
    # Homemade support for [ci skip] no longer needed
    # https://github.blog/changelog/2021-02-08-github-actions-skip-pull-request-and-push-workflows-with-skip-ci/
    # if: "contains(github.event.commits[0].message, '[ci skip]') == false"
    strategy:
      fail-fast: false
      matrix:
        ruby:
          # 3.0 is the last version with no `URI.register_scheme` method
          - "3.0"
          - "3.4"
          - "jruby"
          - "truffleruby"
          - "truffleruby+graalvm"
    env:
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
      COVERAGE: true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Collect coverage info
        run: bundle exec rake

      - name: Coveralls Parallel
        uses: coverallsapp/github-action@master
        continue-on-error: true
        with:
          github-token: ${{ secrets.github_token }}
          flag-name: run-${{ matrix.ruby }}-${{ matrix.gemfile }}
          parallel: true

  finish:
    needs: coverage
    runs-on: ubuntu-latest
    steps:
      - name: Send to Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel-finished: true
